services:
  flink-jobmanager:
    build:
      context: docker-builds/flink
      dockerfile: flink.Dockerfile
    container_name: flink-jobmanager
    hostname: flink-jobmanager
    command: jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    networks:
      - magnumopus_airflow-net

  flink-taskmanager:
    build:
      context: docker-builds/flink
      dockerfile: flink.Dockerfile
    container_name: flink-taskmanager
    hostname: flink-taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - flink-jobmanager
    networks:
      - magnumopus_airflow-net

networks:
  magnumopus_airflow-net:
    external: true