services:

  zookeeper:
    image: zookeeper:3.9.2
    container_name: zookeeper
    restart: always
    # networks:
    #   - magnumopus-airflow-net

  coordinator-server:
    # build:
    #   context: docker-builds/fluss
    #   dockerfile: fluss.Dockerfile
    image: istiyaksiddiquee/fluss-for-magnum:v01
    container_name: coordinator-server
    hostname: coordinator-server
    command: coordinatorServer
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://coordinator-server:0, CLIENT://coordinator-server:9123
        advertised.listeners: CLIENT://coordinator-server:9123
        internal.listener.name: INTERNAL
        remote.data.dir: s3://warehouse/fluss-remote
        s3.endpoint: http://minio2:9000
        s3.access-key: minio
        s3.secret-key: minio123
        s3.path.style.access: true
        datalake.format: iceberg
        datalake.iceberg.type: hive
        datalake.iceberg.uri: thrift://hive-metastore:9083
        datalake.iceberg.warehouse: s3a://warehouse/
        datalake.iceberg.io-impl: org.apache.iceberg.aws.s3.S3FileIO
        datalake.iceberg.s3.endpoint: http://minio2:9000
        datalake.iceberg.s3.path-style-access: true
        datalake.iceberg.client.region: us-east-1
        datalake.iceberg.s3.access-key-id: minio
        datalake.iceberg.s3.secret-access-key: minio123
    ports:
      - "9123:9123"
    depends_on:
      - zookeeper
      - hive-metastore
      - mc-job2
    # networks:
    #   - magnumopus-airflow-net

  tablet-server:
    # build:
    #   context: docker-builds/fluss
    #   dockerfile: fluss.Dockerfile
    image: istiyaksiddiquee/fluss-for-magnum:v01
    container_name: tablet-server
    hostname: tablet-server
    command: tabletServer
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://tablet-server:0, CLIENT://tablet-server:9124
        advertised.listeners: CLIENT://tablet-server:9124
        internal.listener.name: INTERNAL
        remote.data.dir: s3://warehouse/fluss-remote
        s3.endpoint: http://minio2:9000
        s3.access-key: minio
        s3.secret-key: minio123
        s3.path.style.access: true
        datalake.format: iceberg
        datalake.iceberg.type: hive
        datalake.iceberg.uri: thrift://hive-metastore:9083
        datalake.iceberg.warehouse:  s3a://warehouse/
        datalake.iceberg.io-impl: org.apache.iceberg.aws.s3.S3FileIO
        datalake.iceberg.s3.endpoint: http://minio2:9000
        datalake.iceberg.s3.path-style-access: true
        datalake.iceberg.client.region: us-east-1
        datalake.iceberg.s3.access-key-id: minio
        datalake.iceberg.s3.secret-access-key: minio123
    depends_on:
      - coordinator-server
    ports:
      - "9124:9124"
    # networks:
    #   - magnumopus-airflow-net

  trino:
    container_name: trino
    image: trinodb/trino:479
    hostname: trino
    ports:
      - "8000:8080"
    volumes:
      - ./docker-builds/trino:/etc/trino
    # networks:
    #   - magnumopus-airflow-net

  metastore_db:
    image: postgres:17.7
    hostname: metastore_db
    container_name: metastore_db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - metastore_db_volume:/var/lib/postgresql/data
    # networks:
    #   - magnumopus-airflow-net

  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.3-e.15'
    ports:
      - '9083:9083' # Metastore Thrift
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://warehouse/
      S3_ENDPOINT: http://minio2:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db
    # networks:
    #   - magnumopus-airflow-net

  minio2:
    hostname: minio2
    image: 'pgsty/minio:RELEASE.2026-03-25T00-00-00Z-amd64'
    container_name: minio2
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio2_volume:/data
    # networks:
    #   - magnumopus-airflow-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 15

  # This job will create the "warehouse" bucket on Minio
  mc-job2:
    image: 'pgsty/mc:latest'
    container_name: mc-job2
    entrypoint: |
      /bin/bash -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio2:9000 minio minio123 --quiet;
      /usr/bin/mc mb --ignore-existing --quiet myminio/warehouse;
      /usr/bin/mc ls myminio
      "
    depends_on:
      minio2:
        condition: service_healthy
    # networks:
    #   - magnumopus-airflow-net

volumes:
  minio2_volume:
  metastore_db_volume:


# networks:
#   magnumopus-airflow-net:
#     external: true
#     name: magnumopus-airflow-net