version: 2

sources:
  - name: datalake
    database: iceberg
    schema: lakehouse_db

    tables:
      - name: green_taxi_2025_01
      - name: green_taxi_2025_02
      - name: green_taxi_2025_03
      - name: green_taxi_2025_04
      - name: green_taxi_2025_05
      - name: green_taxi_2025_06
      - name: green_taxi_2025_07
      - name: green_taxi_2025_08
      - name: green_taxi_2025_09
      - name: green_taxi_2025_10