datasets:
  taxi:
    column_mapping:
      categorical_features:
        - 'PULocationID'
        - 'DOLocationID'
      numerical_features:
        - 'trip_distance'
      target: 'duration'
      prediction: 'prediction'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - regression_performance
      - num_target_drift
    reference_file: ./datasets/green_tripdata_2022-01.parquet
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
