bronze:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: trino
      port: 8080
      database: warehouse
      schema: bronze
      threads: 1

silver:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: trino
      port: 8080
      database: warehouse
      schema: silver
      threads: 1

gold:
  target: dev
  outputs:
    dev:
      type: trino
      user: admin
      host: trino
      port: 8080
      database: warehouse
      schema: gold
      threads: 1
